### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory when running heatmap.py

### ISSUE THREAD

**Issue by lylyjy** [alessiabertugli/AC-VRNN#2]
I use eth data, and when I run heatmap.py, it occurs that:

Traceback (most recent call last):
  File "/mnt/e/AC-VRNN-master/dataset_processing/heatmap.py", line 286, in <module>
    compute_mean_displacement_eth_ucy(data_dir='/mnt/e/AC-VRNN-master/datasets/eth', delim='\t')
  File "/mnt/e/AC-VRNN-master/dataset_processing/heatmap.py", line 88, in compute_mean_displacement_eth_ucy
    data = read_file(path, delim)
  File "./dataset_processing/dataloader_utils.py", line 34, in read_file
    with open(_path, 'r') as f:
IsADirectoryError: [Errno 21] Is a directory: '/mnt/e/AC-VRNN-master/datasets/eth/test'

My definition is :
if __name__ == '__main__':
    compute_mean_displacement_eth_ucy(data_dir='/mnt/e/AC-VRNN-master/datasets/eth', delim='\t')
    compute_local_heatmaps_eth_ucy(data_dir='/mnt/e/AC-VRNN-master/datasets/eth', out_dir='local_hm_5x5', delim='\t')

Thanks.

**Comment by alessiabertugli** [comment]
Are you using the dataset version provided here https://github.com/huang-xx/STGAT/tree/master/STGAT/datasets?
Moreover, you have to pass the path to the global directory containing all ETH/UCY datasets. 
compute_mean_displacement_eth_ucy(data_dir='/mnt/e/AC-VRNN-master/datasets', delim='\t')
compute_local_heatmaps_eth_ucy(data_dir='/mnt/e/AC-VRNN-master/datasets', out_dir='local_hm_5x5', delim='\t')

**Comment by lylyjy** [comment]
> Are you using the dataset version provided here https://github.com/huang-xx/STGAT/tree/master/STGAT/datasets?
> Moreover, you have to pass the path to the global directory containing all ETH/UCY datasets.
> compute_mean_displacement_eth_ucy(data_dir='/mnt/e/AC-VRNN-master/datasets', delim='\t')
> compute_local_heatmaps_eth_ucy(data_dir='/mnt/e/AC-VRNN-master/datasets', out_dir='local_hm_5x5', delim='\t')

There is still a problem.
In dataloader_utils.py, the function of read_file is the main reason. Especially with open(_path, 'r') as f:
it also occurs that:
Exception has occurred: IsADirectoryError
[Errno 21] Is a directory: '/mnt/e/AC-VRNN-master/datasets/eth'
  File "/mnt/e/AC-VRNN-master/dataset_processing/dataloader_utils.py", line 34, in read_file
    with open(_path, 'r') as f:
  File "/mnt/e/AC-VRNN-master/dataset_processing/heatmap.py", line 90, in compute_mean_displacement_eth_ucy
    data = read_file(path, delim)
  File "/mnt/e/AC-VRNN-master/dataset_processing/heatmap.py", line 288, in <module>
    compute_mean_displacement_eth_ucy(data_dir='/mnt/e/AC-VRNN-master/datasets', delim='tab')

Is it OK in your conmuter? Thanks.

**Comment by lylyjy** [comment]
And how to generate npy document?Thanks.

**Comment by godspeed5** [comment]
I have the same issue. Were you able to fix it?
